export const data_Static = {
  id: 1,
  attributes: {
    Title: "Lehanga",
    Description:
      "Jass Manak is a popular Punjabi singer who has featured on the UK Asian Music Chart and also the Global YouTube Weekly Chart for his songs. Many of his popular singles from his albums, include songs Prada, Lehanga, Suit Punjabi and Boss, amongst others. Jass Manak has worked with Sharry Nexus for many songs. Here’s a list of their hit songs together.",
    createdAt: "2022-01-05T07:25:32.729Z",
    updatedAt: "2022-01-15T11:34:16.526Z",
    publishedAt: "2022-01-05T07:25:34.055Z",
    locale: "en",
    lowest_ask: 2.21,
    highest_ask: 20.25,
    slug: "lehanga",
    royalty_share: 30,
    total_tokens: 300,
    available_token: 105,
    audio_url:
      "https://d2q23p4t0ij9e0.cloudfront.net/Jas_Manak_MP_3_Trimmied_5845c85706.mp3",
    video_url: null,
    image_url: "https://d2q23p4t0ij9e0.cloudfront.net/Picture_1_f13aa1a4b5.png",
    blockchain: "Polygon Mainnet",
    contract_address:
      "https://mumbai.polygonscan.com/address/0x3a0afabe4a82bf429f49deb29e3f563012ce9e34",
    amount_to_be_raised: "100K",
    legal_contract:
      "https://d2q23p4t0ij9e0.cloudfront.net/Contract_Artist_First_98f8d99f2e.pdf",
    lauch_date: "2022-02-01T04:30:00.000Z",
    upcoming_homepage: true,
    artists: {
      data: [
        {
          id: 1,
          attributes: {
            name: "Jas Manak",
            description:
              'Jaspreet Singh Manak (born 12 February 1999) is an Indian playback singer and songwriter.He is known predominantly for the songs "Prada", "Suit Punjabi", "Lehanga", "Viah" and "Boss". His single "Lehanga" has featured on the UK Asian Music Chart and also the Global YouTube weekly chart.',
            createdAt: "2022-01-04T17:15:22.158Z",
            updatedAt: "2022-01-15T10:15:19.710Z",
            publishedAt: "2022-01-04T17:15:23.594Z",
            locale: "en",
            image_thumbnail:
              "https://d2q23p4t0ij9e0.cloudfront.net/jas_manak_fd562db7fc.png",
          },
        },
      ],
    },
    creatives: {
      data: [
        {
          id: 8,
          attributes: {
            name: "Jas-Manak-Picture 1.png",
            alternativeText: "Jas-Manak-Picture 1.png",
            caption: "Jas-Manak-Picture 1.png",
            width: 608,
            height: 1080,
            formats: {
              large: {
                ext: ".png",
                url: "https://d2q23p4t0ij9e0.cloudfront.net/large_Jas_Manak_Picture_1_32977b99f9.png",
                hash: "large_Jas_Manak_Picture_1_32977b99f9",
                mime: "image/png",
                name: "large_Jas-Manak-Picture 1.png",
                path: null,
                size: 1258.51,
                width: 563,
                height: 1000,
              },
              small: {
                ext: ".png",
                url: "https://d2q23p4t0ij9e0.cloudfront.net/small_Jas_Manak_Picture_1_32977b99f9.png",
                hash: "small_Jas_Manak_Picture_1_32977b99f9",
                mime: "image/png",
                name: "small_Jas-Manak-Picture 1.png",
                path: null,
                size: 332.02,
                width: 281,
                height: 500,
              },
              medium: {
                ext: ".png",
                url: "https://d2q23p4t0ij9e0.cloudfront.net/medium_Jas_Manak_Picture_1_32977b99f9.png",
                hash: "medium_Jas_Manak_Picture_1_32977b99f9",
                mime: "image/png",
                name: "medium_Jas-Manak-Picture 1.png",
                path: null,
                size: 720.34,
                width: 422,
                height: 750,
              },
              thumbnail: {
                ext: ".png",
                url: "https://d2q23p4t0ij9e0.cloudfront.net/thumbnail_Jas_Manak_Picture_1_32977b99f9.png",
                hash: "thumbnail_Jas_Manak_Picture_1_32977b99f9",
                mime: "image/png",
                name: "thumbnail_Jas-Manak-Picture 1.png",
                path: null,
                size: 38.51,
                width: 88,
                height: 156,
              },
            },
            hash: "Jas_Manak_Picture_1_32977b99f9",
            ext: ".png",
            mime: "image/png",
            size: 968.07,
            url: "https://d2q23p4t0ij9e0.cloudfront.net/Jas_Manak_Picture_1_32977b99f9.png",
            previewUrl: null,
            provider: "strapi-provider-upload-aws-s3-advanced",
            provider_metadata: null,
            createdAt: "2022-01-05T07:21:24.900Z",
            updatedAt: "2022-01-05T07:21:24.900Z",
          },
        },
        {
          id: 9,
          attributes: {
            name: "Jas-Manak-Picture 2.png",
            alternativeText: "Jas-Manak-Picture 2.png",
            caption: "Jas-Manak-Picture 2.png",
            width: 582,
            height: 1038,
            formats: {
              large: {
                ext: ".png",
                url: "https://d2q23p4t0ij9e0.cloudfront.net/large_Jas_Manak_Picture_2_26be4849e4.png",
                hash: "large_Jas_Manak_Picture_2_26be4849e4",
                mime: "image/png",
                name: "large_Jas-Manak-Picture 2.png",
                path: null,
                size: 616.8,
                width: 561,
                height: 1000,
              },
              small: {
                ext: ".png",
                url: "https://d2q23p4t0ij9e0.cloudfront.net/small_Jas_Manak_Picture_2_26be4849e4.png",
                hash: "small_Jas_Manak_Picture_2_26be4849e4",
                mime: "image/png",
                name: "small_Jas-Manak-Picture 2.png",
                path: null,
                size: 183.67,
                width: 280,
                height: 500,
              },
              medium: {
                ext: ".png",
                url: "https://d2q23p4t0ij9e0.cloudfront.net/medium_Jas_Manak_Picture_2_26be4849e4.png",
                hash: "medium_Jas_Manak_Picture_2_26be4849e4",
                mime: "image/png",
                name: "medium_Jas-Manak-Picture 2.png",
                path: null,
                size: 368.67,
                width: 421,
                height: 750,
              },
              thumbnail: {
                ext: ".png",
                url: "https://d2q23p4t0ij9e0.cloudfront.net/thumbnail_Jas_Manak_Picture_2_26be4849e4.png",
                hash: "thumbnail_Jas_Manak_Picture_2_26be4849e4",
                mime: "image/png",
                name: "thumbnail_Jas-Manak-Picture 2.png",
                path: null,
                size: 24.12,
                width: 87,
                height: 156,
              },
            },
            hash: "Jas_Manak_Picture_2_26be4849e4",
            ext: ".png",
            mime: "image/png",
            size: 448.24,
            url: "https://d2q23p4t0ij9e0.cloudfront.net/Jas_Manak_Picture_2_26be4849e4.png",
            previewUrl: null,
            provider: "strapi-provider-upload-aws-s3-advanced",
            provider_metadata: null,
            createdAt: "2022-01-05T07:21:32.403Z",
            updatedAt: "2022-01-05T07:21:32.403Z",
          },
        },
        {
          id: 10,
          attributes: {
            name: "Jas-Manak-Picture 3.png",
            alternativeText: "Jas-Manak-Picture 3.png",
            caption: "Jas-Manak-Picture 3.png",
            width: 608,
            height: 1082,
            formats: {
              large: {
                ext: ".png",
                url: "https://d2q23p4t0ij9e0.cloudfront.net/large_Jas_Manak_Picture_3_b614d4d76c.png",
                hash: "large_Jas_Manak_Picture_3_b614d4d76c",
                mime: "image/png",
                name: "large_Jas-Manak-Picture 3.png",
                path: null,
                size: 1383.74,
                width: 562,
                height: 1000,
              },
              small: {
                ext: ".png",
                url: "https://d2q23p4t0ij9e0.cloudfront.net/small_Jas_Manak_Picture_3_b614d4d76c.png",
                hash: "small_Jas_Manak_Picture_3_b614d4d76c",
                mime: "image/png",
                name: "small_Jas-Manak-Picture 3.png",
                path: null,
                size: 394.09,
                width: 281,
                height: 500,
              },
              medium: {
                ext: ".png",
                url: "https://d2q23p4t0ij9e0.cloudfront.net/medium_Jas_Manak_Picture_3_b614d4d76c.png",
                hash: "medium_Jas_Manak_Picture_3_b614d4d76c",
                mime: "image/png",
                name: "medium_Jas-Manak-Picture 3.png",
                path: null,
                size: 823.53,
                width: 421,
                height: 750,
              },
              thumbnail: {
                ext: ".png",
                url: "https://d2q23p4t0ij9e0.cloudfront.net/thumbnail_Jas_Manak_Picture_3_b614d4d76c.png",
                hash: "thumbnail_Jas_Manak_Picture_3_b614d4d76c",
                mime: "image/png",
                name: "thumbnail_Jas-Manak-Picture 3.png",
                path: null,
                size: 43.94,
                width: 88,
                height: 156,
              },
            },
            hash: "Jas_Manak_Picture_3_b614d4d76c",
            ext: ".png",
            mime: "image/png",
            size: 851.89,
            url: "https://d2q23p4t0ij9e0.cloudfront.net/Jas_Manak_Picture_3_b614d4d76c.png",
            previewUrl: null,
            provider: "strapi-provider-upload-aws-s3-advanced",
            provider_metadata: null,
            createdAt: "2022-01-05T07:21:56.137Z",
            updatedAt: "2022-01-05T07:21:56.137Z",
          },
        },
      ],
    },
    Video: {
      data: {
        id: 11,
        attributes: {
          name: "JasManak.mp4",
          alternativeText: "JasManak.mp4",
          caption: "JasManak.mp4",
          width: null,
          height: null,
          formats: null,
          hash: "Jas_Manak_e766179174",
          ext: ".mp4",
          mime: "video/mp4",
          size: 16479.17,
          url: "https://d2q23p4t0ij9e0.cloudfront.net/Jas_Manak_e766179174.mp4",
          previewUrl: null,
          provider: "strapi-provider-upload-aws-s3-advanced",
          provider_metadata: null,
          createdAt: "2022-01-05T07:25:01.256Z",
          updatedAt: "2022-01-05T07:25:01.256Z",
        },
      },
    },
    PreviewAudio: {
      data: {
        id: 12,
        attributes: {
          name: "JasManak-MP3-Trimmied.mp3",
          alternativeText: "JasManak-MP3-Trimmied.mp3",
          caption: "JasManak-MP3-Trimmied.mp3",
          width: null,
          height: null,
          formats: null,
          hash: "Jas_Manak_MP_3_Trimmied_5845c85706",
          ext: ".mp3",
          mime: "audio/mpeg",
          size: 1154.65,
          url: "https://d2q23p4t0ij9e0.cloudfront.net/Jas_Manak_MP_3_Trimmied_5845c85706.mp3",
          previewUrl: null,
          provider: "strapi-provider-upload-aws-s3-advanced",
          provider_metadata: null,
          createdAt: "2022-01-05T07:25:17.189Z",
          updatedAt: "2022-01-05T07:25:17.189Z",
        },
      },
    },
    FullAudio: {
      data: {
        id: 13,
        attributes: {
          name: "JasManak-MP3-Full.mp3",
          alternativeText: "JasManak-MP3-Full.mp3",
          caption: "JasManak-MP3-Full.mp3",
          width: null,
          height: null,
          formats: null,
          hash: "Jas_Manak_MP_3_Full_94e7218ce1",
          ext: ".mp3",
          mime: "audio/mpeg",
          size: 5106.98,
          url: "https://d2q23p4t0ij9e0.cloudfront.net/Jas_Manak_MP_3_Full_94e7218ce1.mp3",
          previewUrl: null,
          provider: "strapi-provider-upload-aws-s3-advanced",
          provider_metadata: null,
          createdAt: "2022-01-05T07:25:27.865Z",
          updatedAt: "2022-01-05T07:25:27.865Z",
        },
      },
    },
    asset_attributes: {
      data: [
        {
          id: 1,
          attributes: {
            trait_type: "lyricist",
            value: "Kumar",
            createdAt: "2022-01-05T08:14:00.211Z",
            updatedAt: "2022-01-05T08:14:02.960Z",
            publishedAt: "2022-01-05T08:14:02.956Z",
            display_type: null,
            locale: "en",
          },
        },
        {
          id: 2,
          attributes: {
            trait_type: "Composer",
            value: "ABCD",
            createdAt: "2022-01-05T08:14:21.131Z",
            updatedAt: "2022-01-05T08:14:36.435Z",
            publishedAt: "2022-01-05T08:14:22.822Z",
            display_type: null,
            locale: "en",
          },
        },
        {
          id: 3,
          attributes: {
            trait_type: "song_hash",
            value: "0x123adbc",
            createdAt: "2022-01-05T08:14:58.191Z",
            updatedAt: "2022-01-05T08:15:03.393Z",
            publishedAt: "2022-01-05T08:15:03.390Z",
            display_type: null,
            locale: "en",
          },
        },
        {
          id: 4,
          attributes: {
            trait_type: "song_signed_hash",
            value: "0x12dfa",
            createdAt: "2022-01-05T08:15:32.469Z",
            updatedAt: "2022-01-05T08:15:36.146Z",
            publishedAt: "2022-01-05T08:15:36.143Z",
            display_type: null,
            locale: "en",
          },
        },
        {
          id: 5,
          attributes: {
            trait_type: "Genre",
            value: "Pop, Bollywood",
            createdAt: "2022-01-05T08:16:09.814Z",
            updatedAt: "2022-01-05T08:16:16.802Z",
            publishedAt: "2022-01-05T08:16:16.799Z",
            display_type: null,
            locale: "en",
          },
        },
      ],
    },
    video_cover: {
      data: {
        id: 22,
        attributes: {
          name: "VideoThumbnail.jpeg",
          alternativeText: "VideoThumbnail.jpeg",
          caption: "VideoThumbnail.jpeg",
          width: 1280,
          height: 720,
          formats: {
            large: {
              ext: ".jpeg",
              url: "https://d2q23p4t0ij9e0.cloudfront.net/large_Video_Thumbnail_914b9d44e7.jpeg",
              hash: "large_Video_Thumbnail_914b9d44e7",
              mime: "image/jpeg",
              name: "large_VideoThumbnail.jpeg",
              path: null,
              size: 95.6,
              width: 1000,
              height: 563,
            },
            small: {
              ext: ".jpeg",
              url: "https://d2q23p4t0ij9e0.cloudfront.net/small_Video_Thumbnail_914b9d44e7.jpeg",
              hash: "small_Video_Thumbnail_914b9d44e7",
              mime: "image/jpeg",
              name: "small_VideoThumbnail.jpeg",
              path: null,
              size: 34.25,
              width: 500,
              height: 281,
            },
            medium: {
              ext: ".jpeg",
              url: "https://d2q23p4t0ij9e0.cloudfront.net/medium_Video_Thumbnail_914b9d44e7.jpeg",
              hash: "medium_Video_Thumbnail_914b9d44e7",
              mime: "image/jpeg",
              name: "medium_VideoThumbnail.jpeg",
              path: null,
              size: 62.71,
              width: 750,
              height: 422,
            },
            thumbnail: {
              ext: ".jpeg",
              url: "https://d2q23p4t0ij9e0.cloudfront.net/thumbnail_Video_Thumbnail_914b9d44e7.jpeg",
              hash: "thumbnail_Video_Thumbnail_914b9d44e7",
              mime: "image/jpeg",
              name: "thumbnail_VideoThumbnail.jpeg",
              path: null,
              size: 11.52,
              width: 245,
              height: 138,
            },
          },
          hash: "Video_Thumbnail_914b9d44e7",
          ext: ".jpeg",
          mime: "image/jpeg",
          size: 119.11,
          url: "https://d2q23p4t0ij9e0.cloudfront.net/Video_Thumbnail_914b9d44e7.jpeg",
          previewUrl: null,
          provider: "strapi-provider-upload-aws-s3-advanced",
          provider_metadata: null,
          createdAt: "2022-01-07T09:51:15.294Z",
          updatedAt: "2022-01-07T09:51:15.294Z",
        },
      },
    },
    asset_tiers: {
      data: [
        {
          id: 1,
          attributes: {
            revenue_share: 0.15,
            createdAt: "2022-01-05T08:22:33.951Z",
            updatedAt: "2022-01-14T07:34:55.418Z",
            publishedAt: "2022-01-05T08:22:52.199Z",
            Privilege1: "2 shows entries per year",
            Privilege2: "Birthday Wishes from Artist",
            Privilege3: "Instagram Story by Artist",
            Privilege4: null,
            tier_max_supply: 100,
            tier_current_supply: 100,
            locale: "en",
            asset_tier_mnemonics: "Gold Lehanga",
            tier_id: 5,
          },
        },
        {
          id: 3,
          attributes: {
            revenue_share: 0.05,
            createdAt: "2022-01-05T08:29:28.145Z",
            updatedAt: "2022-01-14T07:24:08.522Z",
            publishedAt: "2022-01-05T08:29:31.678Z",
            Privilege1: "1 Show Entry Per year",
            Privilege2: "Birthday Wishes from Artist",
            Privilege3: null,
            Privilege4: null,
            tier_max_supply: 300,
            tier_current_supply: 300,
            locale: "en",
            asset_tier_mnemonics: "Silver Jind Mahive",
            tier_id: 6,
          },
        },
      ],
    },
    localizations: { data: [] },
  },
};
